# -*- coding: utf-8 -*-
"""AML Mini Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15UbcCsF4CUdY7X7blooJ7PhnccDY7FCg
"""

# =========================================
# FAKE NEWS CLASSIFIER USING WELFake DATASET
# =========================================

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

# -----------------------------
# 1. LOAD DATASET SAFELY
# -----------------------------
df = pd.read_csv(
    "/content/WELFake_Dataset.csv",
    engine="python",
    on_bad_lines="skip",
    quoting=3
)

df.head()
df.info()

# Check missing values
df.isnull().sum()

df = df.fillna("")

df["content"] = df["title"] + " " + df["text"]

df["content"].head()

X = df["content"]         # text
y = df["label"]           # 0 = Fake, 1 = Real

X.shape, y.shape

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(stop_words="english", max_df=0.75)

X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

from sklearn.linear_model import PassiveAggressiveClassifier

model = PassiveAggressiveClassifier(max_iter=70)
model.fit(X_train_tfidf, y_train)

from sklearn.metrics import accuracy_score, confusion_matrix

y_pred = model.predict(X_test_tfidf)

acc = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)

print("Accuracy:", acc)
print("\nConfusion Matrix:\n", cm)

sample_news = ["Government announces new AI-powered agriculture platform for farmers"]

news_tfidf = vectorizer.transform(sample_news)
prediction = model.predict(news_tfidf)

print("Prediction:", "REAL" if prediction[0] == 1 else "FAKE")

import pickle

# Save the trained model
pickle.dump(model, open("fake_news_model.pkl", "wb"))

# Save the TF-IDF vectorizer
pickle.dump(vectorizer, open("tfidf_vectorizer.pkl", "wb"))

print("Model & vectorizer saved successfully!")

!pip install streamlit pyngrok

from pyngrok import ngrok
ngrok.set_auth_token("YOUR_NGROK_TOKEN")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pickle
# 
# # Load model & vectorizer
# model = pickle.load(open("fake_news_model.pkl", "rb"))
# vectorizer = pickle.load(open("tfidf_vectorizer.pkl", "rb"))
# 
# # App Title
# st.title("📰 Fake News Classifier")
# st.subheader("Detect whether a news article is REAL or FAKE using Machine Learning")
# 
# # Input area
# user_input = st.text_area("Enter News Article Text")
# 
# if st.button("Classify"):
#     if user_input.strip() == "":
#         st.warning("Please enter some text to classify.")
#     else:
#         # Vectorize input
#         user_tfidf = vectorizer.transform([user_input])
# 
#         # Predict
#         prediction = model.predict(user_tfidf)[0]
# 
#         # Result
#         if prediction == 1:
#             st.success("✅ This news appears to be **REAL**.")
#         else:
#             st.error("❌ This news appears to be **FAKE**.")
#

import os
os.listdir('/content')

import pickle

# Save the trained model
pickle.dump(model, open("fake_news_model.pkl", "wb"))

# Save the TF-IDF vectorizer
pickle.dump(vectorizer, open("tfidf_vectorizer.pkl", "wb"))

print("Model & vectorizer saved successfully!")

!pip install streamlit
!npm install -g localtunnel

!streamlit run app.py & npx localtunnel --port 8501

!pip install pyngrok

!streamlit run app.py --server.port 8501 & npx localtunnel --port 8501 --subdomain fakestreamlit123

